server.:
   port: 9000

spring:
   application:
      name: steam-config
   cloud: 
      config: 
        server:
           git: 
              default-label: main
              uri: https://github.com/Lixiaolin0814/YC89-S3-Cloud/
              search-paths: /S3-Pro-steam
              username:
              password:
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka

  